"use client";

import jsPDF from "jspdf";

export default function IncidentReport() {

  const generatePDF = () => {
    const doc = new jsPDF();

    doc.setFontSize(22);

    doc.text(
      "Groot AI Incident Report",
      20,
      20
    );

    doc.setFontSize(14);

    doc.text(
      "Incident: Kubernetes Pod Crash",
      20,
      40
    );

    doc.text(
      "Severity: Critical",
      20,
      50
    );

    doc.text(
      "Status: Resolved",
      20,
      60
    );

    doc.text(
      "Generated By: Autonomous AI Ops Engine",
      20,
      70
    );

    doc.setFontSize(16);

    doc.text(
      "Root Cause Analysis",
      20,
      95
    );

    doc.setFontSize(12);

    doc.text(
      "CPU throttling triggered repeated Kubernetes pod restarts, causing infrastructure instability.",
      20,
      110,
      {
        maxWidth: 170,
      }
    );

    doc.setFontSize(16);

    doc.text(
      "AI Remediation Actions",
      20,
      140
    );

    doc.setFontSize(12);

    doc.text(
      "- Restarted affected services",
      20,
      155
    );

    doc.text(
      "- Triggered autoscaling workflows",
      20,
      165
    );

    doc.text(
      "- Rebalanced cluster workloads",
      20,
      175
    );

    doc.text(
      "- Restored service health",
      20,
      185
    );

    doc.setFontSize(16);

    doc.text(
      "Incident Timeline",
      20,
      210
    );

    doc.setFontSize(12);

    doc.text(
      "00:01 - Traffic spike detected",
      20,
      225
    );

    doc.text(
      "00:03 - CPU threshold exceeded",
      20,
      235
    );

    doc.text(
      "00:05 - Kubernetes restart loop detected",
      20,
      245
    );

    doc.save("RootMind-Incident-Report.pdf");
  };

  return (
    <div className="glass rounded-3xl p-6">

      <div className="flex items-center justify-between">

        <div>
          <p className="text-cyan-400 text-sm">
            EXECUTIVE REPORTING
          </p>

          <h2 className="text-3xl font-bold">
            AI Incident Reports
          </h2>
        </div>

        <button
          onClick={generatePDF}
          className="
            px-6 py-3 rounded-2xl
            bg-cyan-500 hover:bg-cyan-400
            transition-all duration-300
            font-semibold
          "
        >
          Generate Report
        </button>
      </div>

      <div className="mt-6 p-5 rounded-2xl bg-black/20 border border-white/5">

        <p className="text-slate-300 leading-8">
          Generate enterprise-grade incident reports with:
          AI-generated root cause analysis,
          remediation workflows,
          outage timelines,
          infrastructure health summaries,
          and operational intelligence.
        </p>
      </div>
    </div>
  );
}